export const RETRIEVE_HOSPITALS = "RETRIEVE_HOSPITALS";
export const RETRIEVE_PROVIDERS = "RETRIEVE_PROVIDERS";
export const RETRIEVE_PATIENTS = "RETRIEVE_PATIENTS";
export const ADD_HOSPITAL = "ADD_HOSPITAL";
export const UPDATE_HOSPITAL = "UPDATE_HOSPITAL";